title: Rahul Dey
logo: "/profile.png?raw=true"

description: >
 <div class="profile-details">
 <strong>Data Engineer</strong><br><br>
 
 <a href="mailto:rahuldey40@outlook.com">rahuldey40@outlook.com</a><br>
 
 <a href="https://www.linkedin.com/in/rahul-dey-1960a919b/">LinkedIn</a><br>
 
 <a href="https://github.com/rahuldeyfb33/">GitHub</a>
 </div>

theme: jekyll-theme-minimal